# Generated by Django 2.2.16 on 2023-01-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20230122_1437'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow byself rejected',
        ),
    ]
